/**
 * End-to-end parity for the browser import pipeline in kpi-core.js.
 *
 * The unit tests cover the pieces; this runs the whole chain the way the page
 * does — read the .xlsx, find the header row, detect the family, extract — over
 * the same fixtures, and asserts it produces byte-identical records to Python's
 * adapters (build/tests/fixtures/kpi_expected.json, regenerated by
 * build/tests/make_golden.py).
 *
 * This exists because three real bugs got past piecewise tests, all of them
 * divergences between the two ports that only appeared on the actual exports:
 *   1. <Relationship> matched with a positional regex, so the sheet path
 *      resolved to "" and zero rows came back (real files write Target before Id).
 *   2. <c> likewise, so no cells were read (real files write s, t, THEN r).
 *   3. the family was detected from row 0 instead of the scanned header row, so
 *      any export with a title above its header was rejected.
 * Python used a real XML parser and scanned for the header, so it was immune to
 * all three — which is exactly why the ports need holding to one another.
 *
 *   node worker/tests/kpi_pipeline.test.mjs
 */
import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";
import { KPI } from "./_kpi_core.mjs";

const golden = JSON.parse(await readFile(
  new URL("../../build/tests/fixtures/kpi_expected.json", import.meta.url), "utf8"));

const M = { kpiFirstSheetRows: KPI.firstSheetRows, kpiFindHeader: KPI.findHeader,
  kpiDetectKind: KPI.detectKind, kpiExtract: KPI.extract, kpiNormHeader: KPI.normHeader };

/** The page's own flow: parse a file, find its header, detect the family, extract. */
async function importFile(name){
  const bytes = await readFile(new URL("../../build/tests/fixtures/" + name, import.meta.url));
  const file = new File([bytes], name);                    // what the file input hands the page
  const rows = await M.kpiFirstSheetRows(file);
  const hi = rows.length ? M.kpiFindHeader(rows) : 0;
  const header = rows.length ? rows[hi].map(M.kpiNormHeader) : [];
  const kind = M.kpiDetectKind(header, name);
  assert.ok(kind, `${name}: the page failed to recognise the report (headers: ${header.filter(Boolean).join(", ")})`);
  const ex = M.kpiExtract(rows, kind, name);
  return { rows, hi, kind, ex };
}

let checks = 0;
for (const [name, want] of Object.entries(golden.fixtures)){
  const { ex, kind, hi } = await importFile(name);

  assert.equal(kind, want.report.kind, `${name}: family detected`);
  // `file` is the local name in both ports; importedAt is stamped at run time.
  const got = { ...ex.report };
  delete got.importedAt;
  assert.deepEqual(got, want.report, `${name}: report metadata differs from Python`);
  assert.deepEqual(ex.units, want.units, `${name}: extracted units differ from Python`);
  checks += 3;

  // Guard the specific shapes the three real bugs broke.
  assert.ok(ex.report.rows > 0, `${name}: zero rows means the sheet part or the cells were not read`);
  if (hi > 0){
    assert.ok(Object.keys(ex.units).length > 0,
      `${name}: a header below row 0 must still extract (the title-row case)`);
  }
  checks += 1;
}

/* The rates fixture is the title-row case (its header is on row 4) and carries a
   header split across rich-text runs — both were silent failures before. */
{
  const { hi, ex } = await importFile("kpi_rates_mini.xlsx");
  assert.equal(hi, 4, "the header row is found below four title rows");
  assert.ok("monthlyBillingRate" in ex.units.U1,
    "a header whose text is split across rich-text runs must still match its alias");
  checks += 2;
}

console.log(`kpi import pipeline (kpi-core.js vs Python golden): ${checks} assertions OK over ${Object.keys(golden.fixtures).length} fixtures`);
